#
# Makefile for the cypress 120 ts drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_CYPRESS120)+= cypress120_ts_i2c_drv.o
obj-$(CONFIG_CYPRESS120)+= cypress_firmware.o
obj-$(CONFIG_CYPRESS120)+= ISSP_Driver_Routines.o
obj-$(CONFIG_CYPRESS120)+= ISSP_Routines.o
